services:
  - type: web
    name: flask-ml-app
    env: docker
    healthCheckPath: /
    # plan: free # 無料プランを明示的に指定する場合（任意）
    
    # 永続ディスクの定義とマウントをここで行います
    disk:
      name: app-data
      mountPath: /app/data
      sizeGB: 1