# disksとservicesをトップレベルに定義
disks:
  # アプリのデータをまとめて保存する永続ディスクを1つだけ定義
  - name: app-data
    # サイズは必要に応じて変更可能 (例: 10GB)
    sizeGB: 1

services:
  - type: web
    name: flask-ml-app
    env: docker
    healthCheckPath: /
    # 上で定義した'app-data'ディスクを、コンテナ内の'/app/data'に接続
    disk:
      name: app-data
      mountPath: /app/data